# UI language. Korean source strings stay inline in the code; English is looked up per line at display time.
# Lines with runtime values (paths, numbers, messages) match $script:UiPatterns; anything unknown is shown as is.
$script:UiEnglish=@{
  '화면 연결 엔진(engine 폴더)이 없습니다. 받은 ZIP 파일을 처음부터 다시 압축 해제해 주십시오.'='The mirroring engine (engine folder) is missing. Extract the downloaded ZIP file again from the start.'
  'codec은 h264 또는 h265여야 합니다.'='codec must be h264 or h265.'
  '잘못된 인코더 이름입니다.'='Invalid encoder name.'
  '잘못된 비트레이트입니다. 예: 12M'='Invalid bit rate. Example: 12M'
  '비트레이트 범위: 100K~200M'='Bit rate range: 100K–200M'
  'arr은 0 또는 1이어야 합니다.'='arr must be 0 or 1.'
  '잘못된 오디오 설정입니다.'='Invalid audio setting.'
  '60Hz 고정과 60fps 초과를 동시에 사용할 수 없습니다.'='A 60Hz lock cannot be combined with more than 60fps.'
  '잘못된 기기 식별자입니다.'='Invalid device identifier.'
  '어느 휴대폰을 연결하시겠습니까?'='Which phone do you want to connect?'
  '연결된 기기가 여러 대입니다. 화면을 보고 싶은 휴대폰을 골라 주십시오.'='Several devices are connected. Choose the phone whose screen you want to see.'
  '1. 휴대폰 잠금을 풀고 데이터 전송 케이블로 연결하십시오.'='1. Unlock the phone and connect it with a data cable.'
  '2. 설정 > 휴대전화 정보 > 소프트웨어 정보에서 ''빌드번호''를 7번 누르십시오.'='2. Go to Settings > About phone > Software information and tap ''Build number'' 7 times.'
  '3. 설정 > 개발자 옵션에서 ''USB 디버깅''을 켜십시오.'='3. Turn on ''USB debugging'' in Settings > Developer options.'
  '4. 휴대폰에 연결 허용 창이 나오면 본인 PC인지 확인하고 허용하십시오.'='4. When the phone asks to allow the connection, confirm it is your PC and allow it.'
  '사용하던 같은 휴대폰을 다시 연결해 주십시오. 다른 휴대폰의 설정은 건드리지 않습니다.'='Reconnect the same phone you were using. Settings of other phones are not changed.'
  '휴대폰은 찾았지만 연결 허용이 필요합니다.'='The phone was found, but the connection must be allowed.'
  '휴대폰 잠금을 풀고 USB 디버깅 허용 창에서 본인 PC를 허용해 주십시오.'='Unlock the phone and allow this PC in the USB debugging prompt.'
  '연결이 잠시 끊겼습니다. 케이블을 다시 꽂거나 무선 연결을 확인해 주십시오.'='The connection dropped briefly. Replug the cable or check the wireless connection.'
  '휴대폰 연결 확인'='Check the phone connection'
  '확인했습니다 · 다시 연결 확인'='Done · Check the connection again'
  '기기 해상도를 읽지 못했습니다.'='Could not read the device resolution.'
  '알 수 없는 연결 환경입니다.'='Unknown connection type.'
  '환경에 맞는 시작값입니다. 최적값은 같은 앱에서 비교해 결정하십시오.'='These are starting values for your setup. Decide the best values by comparing in the same app.'
  '[0 / Enter] 현재 설정 유지 (이미 잘 동작한다면 권장)'='[0 / Enter] Keep current settings (recommended if already working well)'
  '[1] USB 일반: 최대 1024px / 60fps / 8M / 버퍼 50ms'='[1] USB standard: up to 1024px / 60fps / 8M / buffer 50ms'
  '[2] 무선 연결: 최대 1024px / 60fps / 6M / 버퍼 100ms'='[2] Wireless: up to 1024px / 60fps / 6M / buffer 100ms'
  '[3] 낮은 부하 / 30Hz 화면: 최대 800px / 30fps / 4M / 버퍼 50ms'='[3] Low load / 30Hz display: up to 800px / 30fps / 4M / buffer 50ms'
  '새 설정은 주사율을 강제하지 않습니다. 무선 연결은 미리 연결되어 있어야 합니다.'='New settings do not force the refresh rate. A wireless connection must already be set up.'
  '번호 (처음 실행의 Enter: 1)'='Number (Enter on first run: 1)'
  '0~3 중 표시된 번호를 선택하십시오.'='Select one of the numbers shown, 0–3.'
  '하드웨어 인코더를 확인하지 못해 800px/30fps 이하로 시작합니다.'='Could not confirm a hardware encoder; starting at 800px/30fps or lower.'
  '비교할 코덱의 하드웨어 인코더가 없습니다.'='No hardware encoder is available for the codec to compare.'
  '이미 주사율 강제를 사용하지 않습니다.'='Refresh-rate forcing is already off.'
  '표시된 번호를 선택하십시오.'='Select one of the numbers shown.'
  '이 항목은 비교 범위의 끝입니다. 다른 항목을 선택하십시오.'='This item is at the end of its comparison range. Select another item.'
  '같은 앱/장면/스크롤을 각각 30초 동안 재현하십시오. FPS 숫자만으로 판단하지 마십시오.'='Reproduce the same app, scene and scrolling for 30 seconds each. Do not judge by the FPS number alone.'
  'A: 현재 설정 -> B: 한 항목 변경 -> A: 현재 설정 재확인 (총 약 90초)'='A: current settings -> B: one change -> A: current settings again (about 90 seconds total)'
  '준비되면 Enter (실제 사용 창 크기와 모니터를 두 시험에서 같게 유지)'='Press Enter when ready (keep the same window size and monitor for both trials)'
  '같은 장면으로 돌아갈 준비가 되면 Enter'='Press Enter when ready to return to the same scene'
  '마지막으로 같은 장면에서 A를 다시 확인합니다. 준비되면 Enter'='Finally, check A again in the same scene. Press Enter when ready'
  '끊김, 글씨, 조작 지연을 함께 비교하십시오. 애매하거나 나빠졌으면 현재 설정을 유지합니다.'='Compare stutter, text and input delay together. If unclear or worse, the current settings are kept.'
  'B가 두 번의 A보다 좋고 다른 불편이 없으면 1, 그 외는 Enter'='Enter 1 if B was better than both A runs with no other issues; otherwise press Enter'
  '한 항목씩 비교하기'='Compare one item at a time'
  '[1] 끊김 완충 늘리기     [2] 해상도를 낮춰 부하 줄이기'='[1] More stutter buffering     [2] Lower resolution to reduce load'
  '[3] 해상도를 높여 글씨 개선 [4] 버퍼를 줄여 조작 지연 비교'='[3] Higher resolution for sharper text [4] Smaller buffer for less input delay'
  '[5] H.264/H.265 비교      [6] 통신량 줄이기'='[5] Compare H.264/H.265      [6] Reduce data rate'
  '[7] 프레임 상한 낮추기    [8] 프레임 상한 올리기 (최대 60)'='[7] Lower frame cap    [8] Raise frame cap (max 60)'
  '[9] 주사율 강제 끄기     [10] 비트레이트를 높여 압축 화질 개선'='[9] Turn off refresh forcing     [10] Higher bit rate for better quality'
  '시험할 번호 (Enter: 취소)'='Number to try (Enter: cancel)'
  '비교 기록을 저장하지 못했습니다. 설정 저장 여부와는 별개입니다.'='Could not save the comparison record. This does not affect whether settings were saved.'
  '개선을 확인한 후보를 저장했습니다. 이전 설정은 mirrodex.cfg.bak에 있습니다.'='Saved the confirmed improvement. The previous settings are in mirrodex.cfg.bak.'
  '현재 설정을 유지합니다.'='Keeping the current settings.'
  '주사율 복원 파일이 손상되었습니다. refresh-recovery.cfg를 확인하십시오.'='The refresh-rate restore file is damaged. Check refresh-recovery.cfg.'
  '이전 기기의 주사율 복원이 남아 있습니다. 해당 기기를 먼저 연결해 주십시오.'='A refresh-rate restore is pending for a previous device. Connect that device first.'
  '주사율 복원 실패. 기기를 다시 연결하고 실행하십시오. 복원 기록을 보존했습니다.'='Refresh-rate restore failed. Reconnect the device and run again. The restore record was kept.'
  '이전 휴대폰 주사율 설정을 복원했습니다.'='Restored the previous phone refresh-rate setting.'
  '주사율 복구 요청 파일을 확인해 주십시오.'='Check the refresh-rate repair request file.'
  '요청한 갤럭시인지 확인하지 못해 주사율을 바꾸지 않았습니다.'='Could not confirm the requested Galaxy device, so the refresh rate was not changed.'
  '현재 주사율 모드를 읽지 못했습니다. 복구 요청을 보존합니다.'='Could not read the current refresh-rate mode. The repair request is kept.'
  '주사율 복구를 완료하지 못했습니다. 다음 연결 때 다시 확인합니다.'='Could not complete the refresh-rate repair. It will be checked again on the next connection.'
  '주사율 복구를 확인하지 못해 요청을 보존합니다.'='Could not verify the refresh-rate repair; the request is kept.'
  '시험을 중단했습니다. 변경 설정은 저장하지 않았습니다.'='Trial stopped. Changed settings were not saved.'
  'Mirrodex 도우미'='Mirrodex Assistant'
  'Mirrodex - 휴대폰 화면 미러링'='Mirrodex - Phone screen mirroring'
  '확인'='OK'
  '설정 저장 완료. 다음부터 바로 실행합니다.'='Settings saved. Mirrodex will start directly next time.'
  '진행을 완료하지 못했습니다'='Could not finish'
  '휴대폰 연결을 확인한 뒤 도우미를 다시 열어 주십시오. 자세한 내용:'='Check the phone connection, then open the assistant again. Details:'
  '확인하고 닫기'='OK, close'
  'Mirrodex 설정 · 방송에 공유하지 않는 창'='Mirrodex settings · Do not share this window'
  '소리가 휴대폰에서 재생되므로 녹화에는 포함되지 않습니다.'='Sound plays on the phone, so it is not included in the recording.'
  '녹화 파일을 저장했습니다.'='Recording saved.'
  '방송 중 · 재연결 잠금'='Live · Lock reconnects'
  '화면 선명도 · 긴 변 px'='Resolution · px'
  '프레임 상한 · fps'='Frame cap · fps'
  '화질 · 전송량'='Quality · bit rate'
  '영상 완충 · ms'='Video buffer · ms'
  '소리 완충 · ms'='Audio buffer · ms'
  '화면 압축 방식'='Video codec'
  '소리가 나올 곳'='Sound output'
  '노트북'='Computer'
  '휴대폰'='Phone'
  '방송용 · 소리 연결 실패 시 알려주기'='For streaming · Alert if audio fails'
  'Discord에서 공유 창을 다시 선택해야 할 수 있습니다.'='You may need to reselect the shared window in Discord.'
  '변경 적용 · 화면 재연결'='Apply changes · Reconnect'
  '지금 실행 중인 설정 저장'='Save the running settings'
  '정상 설정으로 복원'='Restore known-good settings'
  'Discord 방송 길라잡이'='Discord streaming guide'
  '문제 정보 저장'='Save troubleshooting info'
  '방송 잠금을 먼저 해제해 주십시오.'='Turn off the streaming lock first.'
  '지금 실행 중인 설정을 저장했습니다. 아직 적용하지 않은 선택값은 저장하지 않습니다.'='Saved the running settings. Selections not yet applied are not saved.'
  '저장된 정상 설정이 없습니다. 도우미에서 먼저 화면을 확인해 주십시오.'='No known-good settings are saved. Check the screen in the assistant first.'
  '문제 정보를 저장했습니다.'='Troubleshooting info saved.'
  '지원되는 인코더가 없습니다.'='No supported encoder.'
  '휴대폰 출력보다 큰 해상도는 선택할 수 없습니다.'='A resolution larger than the phone''s output cannot be selected.'
  'Discord로 함께 보기'='Watch together on Discord'
  '1. Windows Discord에서 화면 공유 → Mirrodex 영상 창을 선택하십시오. 설정 창이나 전체 바탕화면은 선택하지 마십시오.'='1. In Windows Discord, choose Share Screen → the Mirrodex video window. Do not choose the settings window or the entire desktop.'
  '2. 소리 공유를 켜고, 계정에서 제공하는 해상도·프레임을 선택하십시오. Mirrodex의 60fps가 Discord의 60fps를 보장하지는 않습니다.'='2. Turn on sound sharing and choose the resolution and frame rate your account offers. Mirrodex at 60fps does not guarantee 60fps on Discord.'
  '4. 짧은 시험 방송에서 시청자에게 소리·입모양·끊김을 확인받으십시오. 시작 전 설정을 맞추고 ''방송 중'' 잠금을 켜십시오.'='4. In a short test stream, ask viewers to confirm sound, lip sync and smoothness. Set everything up first, then turn on the ''Live'' lock.'
  '끊길 때: 먼저 1920px, 필요하면 1600px로 낮춰 보십시오. 프레임은 유지할 수 있습니다. 자글자글하면 전송량을 한 단계 올려 비교하십시오.'='If it stutters: lower to 1920px first, then 1600px if needed. The frame rate can stay the same. If it looks blocky, raise the bit rate one step and compare.'
  '설정으로 돌아가기'='Back to settings'
  '닫기'='Close'
  '길라잡이를 종료했습니다. 확인하지 않은 설정은 저장하지 않았습니다.'='The assistant was closed. Unconfirmed settings were not saved.'
  '알 수 없는 증상입니다.'='Unknown symptom.'
  '화면을 조금 기다렸다가 고르게 보여주는 방법을 시험합니다. 조작 반응도 함께 확인해 주십시오.'='Trying a method that waits briefly to show the screen evenly. Check input response as well.'
  '화면 처리량을 조금 줄여 봅니다. 글씨가 읽기 불편해지지 않는지도 확인해 주십시오.'='Slightly reducing screen processing. Check that text stays readable.'
  '글씨를 조금 더 선명하게 보여주는 방법을 시험합니다. 움직임이 끊기지 않는지도 확인해 주십시오.'='Trying a method that shows text a little sharper. Check that motion does not stutter.'
  '화면을 기다리는 시간을 줄여 봅니다. 움직임이 더 끊기지 않는지도 확인해 주십시오.'='Reducing the time spent waiting for the screen. Check that motion does not stutter more.'
  '휴대폰이 화면을 보내는 방식을 바꿔 봅니다. 부드러움과 반응을 함께 확인해 주십시오.'='Changing how the phone sends the screen. Check smoothness and response together.'
  '보내는 정보량을 줄여 봅니다. 글씨와 영상이 흐려지지 않는지도 확인해 주십시오.'='Reducing the amount of data sent. Check that text and video do not get blurry.'
  '컴퓨터와 휴대폰이 처리하는 양을 줄여 봅니다. 움직임이 덜 자연스러울 수 있습니다.'='Reducing the work for the computer and phone. Motion may look less natural.'
  '화면의 세부 내용을 더 많이 보내 봅니다. 움직임이 끊기지 않는지도 확인해 주십시오.'='Sending more screen detail. Check that motion does not stutter.'
  '현재 화면'='Current screen'
  '바꿔 본 화면'='Changed screen'
  '현재 화면 다시 보기'='Current screen again'
  '같은 앱에서 같은 동작을 해 보십시오. 시험 창의 크기와 위치를 이어서 사용합니다.'='Do the same thing in the same app. The trial window keeps its size and position.'
  '30초 뒤 안내로 돌아옵니다. 시간이 부족하면 짧게 시험하거나 비교를 건너뛸 수 있습니다.'='You will return here after 30 seconds. If short on time, try briefly or skip the comparison.'
  '준비 완료 · 30초 보기'='Ready · Watch 30 seconds'
  '10초만 보기'='Watch 10 seconds only'
  '비교 건너뛰기 · 현재 설정 유지'='Skip comparison · Keep current settings'
  '어느 쪽이 더 편하셨습니까?'='Which felt better?'
  '가운데의 바꿔 본 화면이 더 좋았습니까? 글씨·움직임·반응 중 다른 불편이 생겼다면 현재 화면을 유지하십시오.'='Was the changed screen in the middle better? If text, motion or response got worse in any way, keep the current screen.'
  '비슷하거나 판단하기 어렵습니다 · 현재 설정 유지'='Similar or hard to tell · Keep current settings'
  '바꿔 본 화면이 더 좋습니다 · 이 설정 저장'='The changed screen is better · Save this setting'
  '바꿔 본 화면이 더 불편합니다 · 현재 설정 유지'='The changed screen is worse · Keep current settings'
  '저장하지 않고 지금 설정으로 사용'='Use current settings without saving'
  '문제 정보 저장하고 종료'='Save troubleshooting info and exit'
  '정상 동작했던 설정으로 복원'='Restore settings that worked'
  '직전 설정 변경 취소'='Undo the last settings change'
  '이 환경의 정상 설정이 없습니다.'='No known-good settings for this setup.'
  '이 환경의 직전 설정이 없습니다.'='No previous settings for this setup.'
  '1. 어떻게 연결하셨습니까?'='1. How is the phone connected?'
  '잘 모르겠으면 첫 번째를 선택하십시오. 기기에 맞는 화면 설정은 도우미가 준비합니다.'='If unsure, choose the first option. The assistant prepares screen settings for your device.'
  '케이블로 연결했습니다 · 잘 모르겠으면 선택'='With a cable · Choose this if unsure'
  '이미 무선으로 연결해 사용 중입니다'='Already connected wirelessly'
  '컴퓨터가 오래되었거나 가볍게 사용하고 싶습니다'='My computer is older, or I want a lighter load'
  '2. 휴대폰 화면 확인'='2. Check the phone screen'
  '30초 동안 평소 쓰는 앱을 움직여 보십시오. 휴대폰 자체 화면은 꺼질 수 있습니다. 시험 화면이 닫히면 이 안내로 돌아옵니다.'='Use an app you normally use for 30 seconds. The phone''s own screen may turn off. You will return here when the trial window closes.'
  '30초 동안 화면 보기'='Watch the screen for 30 seconds'
  '3. 화면은 어떠셨습니까?'='3. How did the screen look?'
  '가장 불편한 것 하나를 골라 주십시오. 편하게 보였다면 더 바꿀 필요가 없습니다.'='Choose the one thing that bothered you most. If it looked fine, nothing needs to change.'
  '잘 보입니다 · 이대로 저장하고 사용하기'='Looks good · Save and use as is'
  '움직임이 자꾸 끊깁니다'='Motion keeps stuttering'
  '글씨나 화면이 흐릿합니다'='Text or screen looks blurry'
  '누른 뒤 반응이 늦습니다'='Response after tapping is slow'
  '잘 모르겠습니다 · 화면 다시 보기'='Not sure · Watch again'
  '임시 사용 · 복원 · 문제 정보 저장'='Temporary use · Restore · Save troubleshooting info'
  '어떻게 마치시겠습니까?'='How would you like to finish?'
  '확인하지 않은 설정은 저장하지 않고 사용할 수 있습니다. 정상 설정은 직접 지정했을 때만 바뀝니다.'='You can use unconfirmed settings without saving them. Known-good settings change only when you set them.'
  '현재 화면을 정상 설정으로 지정하고 사용'='Set the current screen as known-good and use it'
  '준비가 완료되었습니다'='All set'
  '다음부터는 Mirrodex를 누르면 바로 시작합니다.'='From now on, clicking Mirrodex starts right away.'
  '마우스로 누르거나 끌어서 휴대폰을 조작하십시오. 끝낼 때는 미러링 창의 X를 누르십시오.'='Control the phone by clicking or dragging with the mouse. To finish, click X on the mirroring window.'
  '불편해지면 미러링 옆 메뉴의 ''도우미로 화면 맞추기''를 누르십시오.'='If anything feels off, click ''Tune the screen with the assistant'' in the menu next to the mirror.'
  '도우미로 화면 다시 맞추기'='Tune the screen again with the assistant'
  '미러링 시작하기'='Start mirroring'
  '이번 비교를 마쳤습니다'='Comparison finished'
  '최대 다섯 가지를 비교했습니다. 완벽한 설정을 찾았다는 뜻은 아닙니다.'='Up to five options were compared. This does not mean the perfect settings were found.'
  '케이블을 PC에 직접 꽂고, 무선이면 공유기 가까이 이동해 보십시오. 휴대폰 자체에서도 끊기는지 확인해 주십시오.'='Plug the cable directly into the PC, or move closer to the router if wireless. Also check whether it stutters on the phone itself.'
  '한 가지 설정만 바꿔 비교합니다'='Comparing one changed setting'
  '현재 → 변경 → 현재 화면을 30초씩 보여드립니다. 좋아졌다고 선택하기 전에는 저장하지 않습니다.'='Shows current → changed → current screens for 30 seconds each. Nothing is saved until you choose the better one.'
  '약 90초 동안 비교하기'='Compare for about 90 seconds'
  '시험이 완료되지 않았습니다'='The trial did not finish'
  '휴대폰 연결을 확인해 주십시오. 시험하던 설정은 저장하지 않았습니다. 현재 설정으로 돌아갑니다.'='Check the phone connection. The trial settings were not saved. Returning to the current settings.'
  '현재 설정 유지하기'='Keep current settings'
  '화면 확인'='Screen check'
  '이 환경에서 화면 맞추기'='Tune the screen for this setup'
  '이 환경에서 저장했던 설정 사용'='Use settings saved for this setup'
  '현재 설정을 그대로 시험하기'='Try the current settings as they are'
  '연결 환경이 달라졌습니다'='Your setup has changed'
  '휴대폰·연결 방식·PC·화면 중 하나가 달라졌습니다. 설정을 자동으로 바꾸지는 않습니다.'='The phone, connection type, PC or display has changed. Settings are not changed automatically.'
  '문제 정보를 저장했습니다'='Troubleshooting info saved'
  '화면이나 기기 식별자는 포함하지 않습니다. 파일은 이 PC에만 저장했습니다.'='No screen content or device identifiers are included. The file was saved only on this PC.'
  '휴대폰 잠금을 풀고 이 PC의 USB 디버깅을 허용해 주십시오.'='Unlock the phone and allow USB debugging for this PC.'
  '휴대폰 연결이 끊겼습니다. 같은 휴대폰을 다시 연결해 주십시오. 케이블·USB 포트 또는 무선 연결을 확인하십시오.'='The phone disconnected. Reconnect the same phone. Check the cable, USB port or wireless connection.'
  '화면을 보내는 인코더를 시작하지 못했습니다. 기기가 지원한다고 보고한 다른 인코더를 한 번 시험할 수 있습니다.'='Could not start the screen encoder. You can try another encoder the device reports as supported once.'
  '소리 연결을 시작하지 못했습니다. 휴대폰 잠금을 풀고 다시 연결해 주십시오. 방송 전에 노트북에서 소리가 나는지 확인하십시오.'='Could not start the audio connection. Unlock the phone and reconnect it. Before streaming, check that sound plays on the computer.'
  '실행을 마치지 못했습니다. 원인을 확정할 수 없어 설정을 자동으로 바꾸지 않습니다.'='Could not finish running. The cause could not be determined, so settings are not changed automatically.'
  '연결을 확인했습니다 · 같은 설정으로 재시도'='Connection checked · Retry with the same settings'
  '다른 인코더로 한 번 시험하기'='Try another encoder once'
  '화면 실행 확인'='Check the screen launch'
  '같은 앱을 움직여 보십시오. 시간이 끝나면 안내로 돌아옵니다. 도중에 닫으면 변경 설정은 채택하지 않습니다.'='Move around in the same app. You will return when time is up. If closed midway, the changed settings are not adopted.'
  '시험 중단 · 설정 유지'='Stop trial · Keep settings'
  '미러링 프로그램을 실행하지 못했습니다.'='Could not start the mirroring program.'
  '시험 실행 응답 시간이 초과됐습니다.'='The trial run timed out.'
  '다른 인코더는 어떠셨습니까?'='How was the other encoder?'
  '화면이 실제로 잘 보이고 움직임도 편했을 때만 저장하십시오.'='Save only if the screen really looked good and motion felt comfortable.'
  '기존 설정 유지'='Keep existing settings'
  '잘 동작했습니다 · 새 설정 저장'='Worked well · Save new settings'
  '변경한 설정을 실행하지 못했습니다'='Could not run the changed settings'
  '저장된 설정은 바꾸지 않았습니다. 변경 전 화면으로 돌아갑니다.'='Saved settings were not changed. Returning to the previous screen.'
  '변경 전 설정으로 다시 열기'='Reopen with the previous settings'
  '빠른 작업'='Quick actions'
  '스크린샷 저장'='Save screenshot'
  '화면 설정'='Screen settings'
  '적용하면 화면과 소리가 잠시 다시 연결되며 이번 실행에만 쓰입니다. 계속 쓰려면 저장하십시오.'='Applying reconnects the screen and sound briefly and lasts only for this session. Save to keep it.'
  '도움말'='Help'
  '도우미로 화면 맞추기'='Tune the screen with the assistant'
  '이 창의 X는 메뉴만 최소화합니다. 미러링을 끝내려면 영상 창의 X를 누르십시오.'='This window''s X only minimizes the menu. To stop mirroring, click X on the video window.'
  '스크린샷을 저장했습니다.'='Screenshot saved.'
  '스크린샷을 저장하지 못했습니다. 휴대폰 연결을 확인해 주십시오.'='Could not save the screenshot. Check the phone connection.'
  '이 휴대폰 연결하기'='Connect this phone'
  '연결된 휴대폰은 이미 다른 Mirrodex 창에서 미러링 중입니다. 다른 휴대폰을 케이블이나 무선으로 연결하십시오.'='The connected phone is already mirrored in another Mirrodex window. Connect another phone by cable or wirelessly.'
  '무선으로 연결하기 · 케이블 없이'='Connect wirelessly · No cable'
  '이 휴대폰은 이미 미러링 중입니다'='This phone is already being mirrored'
  '열려 있는 Mirrodex 창을 사용하십시오. 다른 휴대폰을 보려면 메뉴의 ''다른 휴대폰 추가 연결''을 누르십시오.'='Use the Mirrodex window that is already open. To see another phone, click ''Connect another phone'' in its menu.'
  '전면 카메라'='Front camera'
  '후면 카메라'='Back camera'
  '휴대폰 화면 전체'='Whole phone screen'
  '녹화 중입니다. 중지하면 파일이 저장됩니다.'='Recording. The file is saved when you stop.'
  '녹화 중지 · 파일 저장'='Stop recording · Save file'
  '화면 녹화 시작'='Start recording'
  '미러링 창을 항상 위에 표시'='Keep the mirror window on top'
  '보여줄 화면'='What to show'
  '보여줄 화면 바꾸기'='Change what to show'
  '연결'='Connection'
  '무선으로 전환'='Switch to wireless'
  '다른 휴대폰 추가 연결'='Connect another phone'
  '화면 설정 접기'='Hide screen settings'
  '화면 설정 펼치기'='Show screen settings'
  '무선 연결로 전환하는 중입니다…'='Switching to wireless…'
  '무선으로 전환했습니다. 이제 케이블을 뽑아도 됩니다.'='Switched to wireless. You can unplug the cable now.'
  '스크린샷을 저장하는 중입니다…'='Saving the screenshot…'
  '3. 알림을 숨기려면 메뉴의 ''보여줄 화면 바꾸기''에서 앱 하나만 방송하십시오. 헤드폰을 쓰면 마이크로 소리가 다시 들어가는 것을 줄일 수 있습니다.'='3. To hide notifications, stream one app only from ''Change what to show'' in the menu. Headphones reduce sound leaking back into the microphone.'
  '이름으로 찾기'='Search by name'
  '앱 목록을 불러오지 못했습니다. 휴대폰 잠금을 풀고 다시 시도해 주십시오.'='Could not load the app list. Unlock the phone and try again.'
  '지금처럼 휴대폰 화면을 그대로 보여 줍니다'='Shows the phone screen as it is'
  '앱 하나만'='One app only'
  '방송용 · 알림과 다른 앱은 보이지 않습니다 (Android 10 이상)'='For streaming · Notifications and other apps stay hidden (Android 10+)'
  '휴대폰 카메라를 PC 화면에 띄웁니다 (Android 12 이상)'='Shows the phone''s camera on the PC (Android 12+)'
  '보여줄 화면을 고르십시오'='Choose what to show'
  '바꾸면 화면이 잠시 다시 연결됩니다. 카메라는 PC 마이크 대신 휴대폰 마이크 소리를 씁니다.'='Changing this reconnects the screen briefly. Camera mode uses the phone''s microphone.'
  '이 화면 보여 주기'='Show this'
  '앱 목록을 불러오는 중입니다…'='Loading apps…'
  '방송할 앱을 고르십시오'='Choose the app to show'
  '고른 앱만 새 화면에 열립니다. 휴대폰 알림과 다른 앱은 보이지 않습니다.'='Only this app opens, on a separate screen. Phone notifications and other apps stay hidden.'
  '이 앱만 보여 주기'='Show only this app'
  '휴대폰이 Wi-Fi에 연결되어 있지 않습니다. 휴대폰과 PC를 같은 Wi-Fi에 연결해 주십시오.'='The phone is not on Wi-Fi. Connect the phone and the PC to the same Wi-Fi.'
  '휴대폰을 무선 연결 모드로 바꾸지 못했습니다. 휴대폰 잠금을 풀고 다시 시도해 주십시오.'='Could not switch the phone to wireless mode. Unlock the phone and try again.'
  '무선 연결에 실패했습니다. 휴대폰과 PC가 같은 Wi-Fi에 있는지 확인해 주십시오.'='Could not connect wirelessly. Check that the phone and the PC are on the same Wi-Fi.'
  '무선으로 연결하기'='Connect wirelessly'
  '1. 휴대폰과 PC를 같은 Wi-Fi에 연결하십시오.'='1. Connect the phone and the PC to the same Wi-Fi.'
  '2. 휴대폰 설정 > 개발자 옵션에서 ''무선 디버깅''을 켜십시오.'='2. On the phone, turn on ''Wireless debugging'' in Settings > Developer options.'
  '3. ''무선 디버깅''을 눌러 들어간 뒤 ''페어링 코드로 기기 페어링''을 누르십시오.'='3. Open ''Wireless debugging'' and tap ''Pair device with pairing code''.'
  '휴대폰에 6자리 코드와 IP 주소·포트가 나타나면 다음으로 넘어가십시오.'='When the phone shows a 6-digit code and an IP address and port, continue.'
  '코드가 보입니다 · 다음'='I see the code · Next'
  '케이블로 연결하기'='Use a cable instead'
  '페어링 코드 입력'='Enter the pairing code'
  '휴대폰 화면에 보이는 값을 그대로 입력하십시오. 찾은 주소가 있으면 미리 채워 두었습니다.'='Type the values shown on the phone. An address found on the network is filled in already.'
  'IP 주소 및 포트'='IP address & port'
  'Wi-Fi 페어링 코드'='Wi-Fi pairing code'
  '6자리 숫자'='6 digits'
  '페어링하고 연결하기'='Pair and connect'
  'IP 주소와 포트를 192.168.0.10:37123 형식으로 입력해 주십시오.'='Enter the IP address and port like 192.168.0.10:37123.'
  '페어링 코드는 숫자 6자리입니다.'='The pairing code is 6 digits.'
  '페어링하지 못했습니다. 코드가 바뀌었을 수 있습니다. 휴대폰의 새 코드와 주소로 다시 입력해 주십시오.'='Pairing failed. The code may have changed. Enter the new code and address from the phone.'
  '다시 확인해 주십시오'='Please check again'
  '다시 입력하기'='Enter again'
  '연결 주소 입력'='Enter the connection address'
  '페어링했습니다. 무선 디버깅 화면 맨 위의 ''IP 주소 및 포트''를 입력하십시오. 페어링 때와 포트가 다릅니다.'='Paired. Enter the ''IP address & port'' shown at the top of the Wireless debugging screen. Its port differs from the pairing port.'
  '연결하기'='Connect'
  '다른 휴대폰의 연결 창을 여는 중입니다. 휴대폰을 케이블이나 무선으로 연결하십시오.'='Opening a connection window for another phone. Connect it by cable or wirelessly.'
  '이미 설치되어 있습니다'='Mirrodex is already installed'
  '시작 메뉴나 바탕화면의 Mirrodex로 실행하십시오. 제거는 Windows 설정 > 앱에서 할 수 있습니다.'='Start Mirrodex from the Start menu or the desktop. You can remove it in Windows Settings > Apps.'
  'Mirrodex를 이 PC에 설치합니다'='Install Mirrodex on this PC'
  '시작 메뉴와 바탕화면에 바로가기를 만들고, Windows 설정 > 앱에서 제거할 수 있게 등록합니다. 관리자 권한은 필요하지 않습니다.'='Creates Start menu and desktop shortcuts and registers Mirrodex in Windows Settings > Apps for removal. No administrator rights are needed.'
  '설치하기'='Install'
  '설치를 마쳤습니다'='Installation complete'
  '시작 메뉴나 바탕화면의 Mirrodex로 실행하십시오. 지금 연 압축 해제 폴더는 지워도 됩니다.'='Start Mirrodex from the Start menu or the desktop. You can delete the extracted folder now.'
  'Mirrodex 실행하기'='Open Mirrodex'
  'Mirrodex를 제거하시겠습니까?'='Remove Mirrodex?'
  '프로그램, 저장된 설정, 바로가기를 지웁니다. 녹화 파일과 스크린샷(동영상·사진 폴더의 Mirrodex)은 남습니다.'='Removes the program, its saved settings and shortcuts. Recordings and screenshots (Mirrodex in your Videos and Pictures folders) are kept.'
  '제거하기'='Remove'
  '업데이트 확인'='Check for updates'
  '업데이트를 확인하는 중입니다…'='Checking for updates…'
  '업데이트를 확인하지 못했습니다. 인터넷 연결을 확인해 주십시오.'='Could not check for updates. Check your internet connection.'
  '내려받은 업데이트 파일이 손상되었습니다. 지금 버전은 바꾸지 않았습니다.'='The downloaded update is damaged. Your current version was not changed.'
  '업데이트 파일에 Mirrodex 프로그램이 없습니다. 지금 버전은 바꾸지 않았습니다.'='The update file does not contain Mirrodex. Your current version was not changed.'
  '다른 Mirrodex 창이 열려 있어 업데이트할 수 없습니다. 모든 미러링 창을 닫은 뒤 다시 실행해 주십시오.'='Another Mirrodex window is open, so the update cannot be installed. Close all mirroring windows and start Mirrodex again.'
  '업데이트를 설치하는 중입니다'='Installing the update'
  '잠시 뒤 새 버전으로 다시 시작합니다. 창을 닫지 마십시오.'='Mirrodex restarts with the new version in a moment. Do not close this window.'
  '설정, 녹화 파일, 스크린샷은 그대로 남습니다.'='Your settings, recordings and screenshots are kept.'
  '새 버전이 있습니다'='A new version is available'
  '지금 업데이트하기'='Update now'
  '내일 다시 알림'='Remind me tomorrow'
  '이 버전 건너뛰기'='Skip this version'
  '업데이트하지 못했습니다'='Could not update'
  '지금 버전으로 계속합니다. 나중에 GitHub의 Releases에서 직접 받을 수도 있습니다.'='Continuing with the current version. You can also download it later from Releases on GitHub.'
  '지금 버전으로 계속하기'='Continue with the current version'
  '화면'='Screen'
  '바꾸기'='Change'
  '무선 연결'='Wireless'
  '케이블 연결'='Cable'
  '재연결 잠금'='Reconnection locked'
  '저장된 설정'='Saved settings'
  '이번 실행에만 쓰는 설정'='This session only'
  '파일 위치 열기'='Open file location'
  '화면 녹화 시작 · 동영상 폴더'='Record screen · Videos folder'
  '스크린샷 저장 · Alt+]'='Save screenshot · Alt+]'
  '시작할 때 녹화 · 다음 실행부터'='Record at start · From next launch'
  '경기 표시 · Alt+['='Mark match · Alt+['
  '녹화 중일 때만 경기를 표시할 수 있습니다. 먼저 화면 녹화를 시작하십시오.'='Matches can be marked only while recording. Start recording first.'
  'Alt+[, Alt+] 단축키를 다른 프로그램이 쓰고 있습니다. 이 창에서는 버튼으로 눌러 주십시오.'='Another program is using Alt+[ or Alt+]. Use the buttons in this window instead.'
  '포켓몬 챔피언스 실행 · 잠근 채 시작'='Open Pokémon Champions · Start locked'
  '휴대폰 화면 켜 두기'='Keep the phone screen on'
  'PC 컨트롤러를 휴대폰에 전달'='Send the PC controller to the phone'
  '항상 위에 표시 · 미러링 창'='Keep on top · Mirror window'
  '도우미로 화면 맞추기 · 불편한 점을 한 가지씩 비교합니다'='Tune with the assistant · Compares one discomfort at a time'
  '화면 설정 접기 · 바꾼 값은 적용하기 전까지 점선으로 표시됩니다'='Hide screen settings · Values not applied yet are dashed'
  '화면 설정 펼치기 · 선명도, 프레임, 전송량, 소리, 게임 옵션'='Show screen settings · Resolution, fps, bit rate, sound, game options'
  '지금 실행 중인 값입니다.'='These are the running values.'
  '같은 설정으로 다시 연결'='Reconnect with the same settings'
  '화면이 잠시 다시 연결되는 작업입니다. Discord에서는 공유 창을 다시 골라야 할 수 있습니다.'='Marks an action that briefly reconnects the screen. In Discord you may need to pick the shared window again.'
  '파일을 찾지 못했습니다. 옮기거나 지웠을 수 있습니다.'='The file was not found. It may have been moved or deleted.'
  '다른 선택'='Other options'
  '찾는 이름이 없습니다. 다른 글자로 찾아 보십시오.'='No matching name. Try other letters.'
  '2번 바꿔 본 화면이 앞뒤의 1번 현재 화면보다 좋았습니까? 글씨·움직임·반응 중 다른 불편이 생겼다면 현재 화면을 유지하십시오.'='Was 2, the changed screen, better than 1, the current screen before and after it? If text, motion or response got worse in any way, keep the current screen.'
  '다른 방법으로 마치기 · 임시 사용, 복원, 문제 정보 저장'='Finish another way · Temporary use, restore, troubleshooting info'
}
$script:UiPatterns=@(
  @('^(.+)px · 최대 (.+)fps · (.+)$','{0}px · up to {1}fps · {2}'),
  @('^(.+) · 케이블 연결$','{0} · Cable'),
  @('^(.+) · 무선 연결$','{0} · Wireless'),
  @('^녹화 중 (.+)$','Recording {0}'),
  @('^경기를 표시했습니다 · (.+)$','Match marked · {0}'),
  @('^적용하지 않은 값 (.+)개$','{0} not applied yet'),
  @('^약 (.+)초 남았습니다$','About {0}s left'),
  @('^(.+): (.+) → (.+)$','{0}: {1} → {2}'),
  @('^(.+) 실행 실패$','{0} failed to run'),
  @('^(.+) 응답 시간 초과 \((.+) ms\)\. USB 연결을 확인해 주십시오\.$','{0} timed out ({1} ms). Check the USB connection.'),
  @('^설정 형식 오류: (.+)$','Invalid settings format: {0}'),
  @('^중복된 설정: (.+)$','Duplicate setting: {0}'),
  @('^알 수 없는 설정: (.+)$','Unknown setting: {0}'),
  @('^잘못된 숫자 설정: (.+)$','Invalid number setting: {0}'),
  @('^설정 범위 초과: (.+)$','Setting out of range: {0}'),
  @('^ADB 기기 조회 실패: (.*)$','Could not list ADB devices: {0}'),
  @('^기기 검사 실패: (.*)$','Device check failed: {0}'),
  @('^인코더 검사 실패: (.*)$','Encoder check failed: {0}'),
  @('^기기: (.*)$','Device: {0}'),
  @('^미러링 시작: (.+), 버퍼 (.+)ms$','Mirroring: {0}, buffer {1}ms'),
  @('^녹화 파일 저장: (.+)$','Recording saved: {0}'),
  @('^미러링 종료 오류 \((.+)\)$','Mirroring exited with an error ({0})'),
  @('^(.*) 원본 설정을 보존하고 다시 설정합니다\.$','{0} The original settings were kept; setting up again.'),
  @('^현재:\s*(.*)$','Current: {0}'),
  @('^Mirrodex · (.+) · 약 (.+) 초$','Mirrodex · {0} · about {1}s'),
  @('^앱 하나만 · (.+)$','One app only · {0}'),
  @('^(.+) · (.+)px · 최대 (.+)fps$','{0} · {1}px · up to {2}fps'),
  @('^설치 위치: (.+)$','Install location: {0}'),
  @('^Mirrodex (.+) · 약 (.+) MB$','Mirrodex {0} · about {1} MB'),
  @('^Mirrodex (.+)을 설치할 수 있습니다\. 지금 버전은 (.+)입니다\.$','Mirrodex {0} is available. You have {1}.'),
  @('^최신 버전입니다\. 지금 버전: (.+)$','Mirrodex is up to date. Current version: {0}'),
  @('^새 버전 (.+)이 있습니다\. 개발 폴더라서 자동으로 바꾸지 않습니다\.$','Version {0} is available. This is a development folder, so it is not updated automatically.'),
  @('^새 버전 (.+)이 있습니다\. 미러링을 끝내고 Mirrodex를 다시 실행하면 설치합니다\.$','Version {0} is available. It installs the next time you start Mirrodex after mirroring ends.')
)
# Per-PC interface preferences (language, always on top). Kept out of mirrodex.cfg so device settings stay separate.
$script:UiPreferences=$null
$script:PreferencesFile=Join-Path $PSScriptRoot 'preferences.cfg'
function Get-UiPreference ($Key, $Default) {
  if ($null -eq $script:UiPreferences) {
    $script:UiPreferences=@{}
    # language.cfg: the language choice of earlier builds, read once as a fallback.
    foreach ($path in @($script:PreferencesFile, (Join-Path (Split-Path $script:PreferencesFile) 'language.cfg'))) {
      try { foreach ($line in [IO.File]::ReadAllLines($path)) { if ($line -match '^(\w+)=(.*)$' -and -not $script:UiPreferences.ContainsKey($Matches[1])) { $script:UiPreferences[$Matches[1]]=$Matches[2] } } } catch {}
    }
  }
  if ($script:UiPreferences.ContainsKey($Key)) { return $script:UiPreferences[$Key] }
  return $Default
}
function Set-UiPreference ($Key, $Value) {
  [void](Get-UiPreference $Key $null); $script:UiPreferences[$Key]=[string]$Value
  try { [IO.File]::WriteAllLines($script:PreferencesFile,[string[]]@($script:UiPreferences.GetEnumerator() | Sort-Object Key | ForEach-Object { "$($_.Key)=$($_.Value)" })) } catch {}
}
function Get-UiLanguage { if ((Get-UiPreference 'lang' 'en') -eq 'ko') { return 'ko' } else { return 'en' } }
function Set-UiLanguage ($Language) { Set-UiPreference 'lang' $Language }
function Convert-UiLine ([string]$Line) {
  $key=$Line.Trim()
  if (-not $key) { return $Line }
  if ($script:UiEnglish.ContainsKey($key)) { return $Line.Replace($key,$script:UiEnglish[$key]) }
  foreach ($pattern in $script:UiPatterns) {
    $match=[regex]::Match($key,$pattern[0])
    if ($match.Success) {
      $values=@($match.Groups | Select-Object -Skip 1 | ForEach-Object { Convert-UiLine $_.Value })
      return $Line.Replace($key,($pattern[1] -f $values))
    }
  }
  return $Line
}
function T ([string]$Text) {
  if (-not $Text -or (Get-UiLanguage) -eq 'ko') { return $Text }
  return (@($Text -split "`n" | ForEach-Object { Convert-UiLine $_ }) -join "`n")
}

